---
apiVersion: batch/v1beta1
kind: CronJob
metadata:
    name: zoomiebot.pagasa-archiver
    labels:
        name: zoomiebot.pagasa-archiver
        toolforge: tool
spec:
    schedule: "*/10 * * * *"
    concurrencyPolicy: Replace
    jobTemplate:
        spec:
            template:
                metadata:
                    labels:
                        toolforge: tool
                spec:
                    containers:
                        -   name: zoomiebot-pagasa-archiver
                            image: docker-registry.tools.wmflabs.org/toolforge-bullseye-sssd:latest
                            command: [
                              # Start sh first to get run .profile data
                                    "/usr/bin/sh",
                              # Initialize environment
                                    "/data/project/zoomiebot/project/scripts/one-off.sh",
                              # Script to start
                                    "pagasa-archiver"
                            ]
                            workingDir: /data/project/zoomiebot
                            env:
                                -   name: HOME
                                    value: /data/project/zoomiebot
                            imagePullPolicy: Always
                    restartPolicy: OnFailure
