name: Build and Deploy

on:
    push:
        branches:
            - 'master'
    pull_request:

jobs:
    build:
        name: Build
        runs-on: ubuntu-latest
        steps:
            - name: Checking out repo
              uses: actions/checkout@v2
            - name: Installing dependencies
              run: npm ci
            - name: Build web components
              run: npm run build:web
            - name: Building bot
              run: npm run build:bot
    deploy:
        name: Deploy to Toolforge
        needs: build
        if: ${{ github.ref == 'refs/heads/master' }}
        runs-on: ubuntu-latest
        environment:
            name: toolforge
            url: https://zoomiebot.toolforge.org

        steps:
            - name: Checkout code
              uses: actions/checkout@v2
            - name: Install SSH Key
              uses: shimataro/ssh-key-action@v2
              with:
                  key: ${{ secrets.TOOLFORGE_SSH_KEY }}
                  name: id_ed25519
                  known_hosts: ${{ secrets.TOOLFORGE_KNOWN_HOSTS }}
                  config: ${{ secrets.TOOLFORGE_CONFIG }}
            - name: Pull latest commit
              run: ssh login.toolforge.org \
                become zoomiebot \
                  bash -c /data/project/zoomiebot/project/scripts/update.sh
